routes/web.php
<?php

use App\Http\Controllers\ContactanosController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\homeController;
use App\Http\Controllers\pruebaController;
use App\Http\Controllers\CursoController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
El mensaje de entrada
Route::get('/', function () {
    return view('welcome');
});
*/

Route::get('/', homeController::class)->name('home');
Route::resource('cursos', CursoController::class);
Route::view('nosotros', 'nosotros')->name('nosotros');
Route::resource('contactanos', ContactanosController::class);

/*
Esto es cuando despues de haber trabajo con un nombre de ruta y quisiste cambiarlo
para no cambiar todas las rutas del sistema se cambia con names y parameters.
Route::resource('asignaturas', CursoController::class)
    ->parameters(['asignaturas' => 'curso'])
    ->names('cursos');
    */

/*Route::get('cursos', [CursoController::class,'index'])->name('cursos.index');
Route::get('cursos/create', [CursoController::class,'create'])->name('cursos.create');
Route::get('cursos/{curso}', [CursoController::class,'show'])->name('cursos.show');
Route::get('cursos/{curso}/edit', [CursoController::class,'edit'])->name('cursos.edit');
Route::post('cursos', [CursoController::class,'store'])->name('cursos.store');
Route::put('cursos/{curso}', [CursoController::class,'update'])->name('cursos.update');
Route::delete('cursos/{curso}', [CursoController::class,'destroy'])->name('cursos.destroy');*/
/*Route::get('cursos/{curso}', function ($curso) {
    return 'Curso: ' . $curso;
});*/

/*
    Si quiero que un parametro sea opcional hay que agregar un signo ? 
    (al final de la variable)

Route::get('cursos/{curso}/{categoria?}', function ($curso, $categoria = null) {
    return 'Curso: ' . $curso . ' categoria: ' . $categoria;
});*/

app/Models/Curso.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Curso extends Model
{
    use HasFactory;

    //protected $fillable = ['name', 'description', 'category'];

    protected $guarded = [];

    public function getRouteKeyName()
    {
        return 'slug';
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/ContactanosController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreContactanos;
use App\Mail\ContactanosMailable;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;

class ContactanosController extends Controller
{

    public function index()
    {

        return view('contactanos.index');
    }

    public function store(StoreContactanos $request)
    {
        $correo = new ContactanosMailable($request->all());

        Mail::to('lgo80@yahoo.com.ar')->send($correo);

        return redirect()->route('contactanos.index')
            ->with(
                'info',
                'La consulta fue enviada correctamente'
            );
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/CursoController.php
<?php

namespace App\Http\Controllers;

use App\Models\Curso;
use Illuminate\Http\Request;
use App\Http\Requests\StoreCurso;

class CursoController extends Controller
{

    public function index()
    {

        $cursos = Curso::paginate();
        return view('cursos.index', compact('cursos'));
    }

    public function create()
    {
        return view('cursos.create');
    }

    public function show(Curso $curso)
    {
        return view('cursos.show', ['curso' => $curso]);
    }

    public function edit(Curso $curso)
    {
        return view('cursos.edit', compact('curso'));
    }

    public function update(Curso $curso, StoreCurso $request)
    {

       /* $curso->name = $request->txtName;
        $curso->description = $request->txtDescription;
        $curso->category = $request->txtCategory;

        $curso->save();*/

        $curso->update($request->all());

        return redirect()->route('cursos.show', $curso);
    }

    public function store(StoreCurso $request)
    {

        /*$curso = new Curso();

        $curso->name = $request->txtName;
        $curso->description = $request->txtDescription;
        $curso->category = $request->txtCategory;

        $curso->save();*/

        $curso = Curso::create($request->all());

        return redirect()->route('cursos.show', $curso);
    }

    public function destroy(Curso $curso)
    {

        /*$curso = new Curso();

        $curso->name = $request->txtName;
        $curso->description = $request->txtDescription;
        $curso->category = $request->txtCategory;

        $curso->save();*/

        $curso->delete();

        return redirect()->route('cursos.index', $curso);
    }
}

app/Http/Controllers/homeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class homeController extends Controller
{
    
    public function __invoke()
    {
        return view("home");
    }

}

app/Http/Controllers/pruebaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class pruebaController extends Controller
{
    /**
     * Handle the incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function __invoke(Request $request)
    {
        return 'Es la pagina de prueba';
    }
}

resources/views/contactanos/index.blade.php
@extends('layouts.plantilla')

@section('title', 'Contactanos')

@section('content')
    <h1>Deje un mensaje</h1>
    <form action="{{ route('contactanos.store') }}" method="POST">
        @csrf
        <label>
            Nombre:
            <br>
            <input type="text" name="nombre" />
        </label>
        @error('nombre')
            <p><strong>{{ $message }}</strong></p>
        @enderror
        <br>
        <label>
            Correo:
            <br>
            <input type="text" name="correo" />
        </label>
        @error('correo')
            <p><strong>{{ $message }}</strong></p>
        @enderror
        <br>
        <label>
            Asunto:
            <br>
            <input type="text" name="asunto" />
        </label>
        <br>
        <label>
            mensaje:
            <br>
            <textarea name="mensaje" rows="5"></textarea>
        </label>
        @error('mensaje')
            <p><strong>{{ $message }}</strong></p>
        @enderror
        <br>
        <button type="submit">Enviar consulta</button>
    </form>

    @if (session('info'))
        <script>
            alert("{{session('info')}}");

        </script>
    @endif
@endsection

resources/views/cursos/create.blade.php
@extends('layouts.plantilla')

@section('title', 'Crear curso')

@section('content')
    <h1>Estas en la pagina de crear cursos</h1>
    <form action="{{ route('cursos.store') }}" method="POST">
        @csrf
        <label for="name">Nombre: </label><br />
        <input type="text" name="name" id="name" value="{{ old('name') }}" /><br />
        @error('name')
            <small>* {{ $message }}</small>
        @enderror
        <br /><br />
        <label for="description">Descripción: </label><br />
        <textarea rows="5" name="description" id="description">{{ old('description') }}</textarea><br />
        @error('description')
            <small>* {{ $message }}</small>
        @enderror
        <br /><br />
        <label for="category">Categoria: </label><br />
        <input type="text" name="category" id="category" value="{{ old('category') }}" /><br />
        @error('category')
            <small>* {{ $message }}</small>
        @enderror
        <br /><br />
        <button type="submit">Grabar</button>
    </form>
@endsection

resources/views/cursos/edit.blade.php
@extends('layouts.plantilla')

@section('title', 'Editar curso')

@section('content')
    <h1>Estas en la pagina de crear cursos</h1>
    <form action="{{ route('cursos.update', $curso) }}" method="POST">
        @csrf
        @method('put')
        <label for="name">Nombre: </label><br />
        <input type="text" name="name" id="name" value="{{ old('name',$curso->name) }}" /><br />
        @error('name')
            <small>* {{ $message }}</small>
        @enderror
        <br /><br />
        <label for="description">Descripción: </label><br />
        <textarea rows="5" name="description" id="description">{{ old('description',$curso->description) }}</textarea><br />
        @error('description')
            <small>* {{ $message }}</small>
        @enderror
        <br /><br />
        <label for="category">Categoria: </label><br />
        <input type="text" name="category" id="category" value="{{ old('category',$curso->category) }}" /><br />
        @error('category')
            <small>* {{ $message }}</small>
        @enderror
        <br /><br />
        <button type="submit">Editar</button>
    </form>
@endsection

resources/views/cursos/index.blade.php
@extends('layouts.plantilla')

@section('title', 'Lista de cursos')

@section('content')
    <h1>Estas en la pagina de cursos</h1>
    <a href="{{ route('cursos.create') }}">Crear curso</a>
    <ul>
        @foreach ($cursos as $curso)
            <li>
                <a href="{{ route('cursos.show', $curso) }}">
                    {{ $curso->name }}
                </a>
            </li>
        @endforeach
    </ul>

    {{ $cursos->links() }}
@endsection

resources/views/cursos/show.blade.php
@extends('layouts.plantilla')

@section('title', 'Curso elegido')

@section('content')
    <h1>Estas en la pagina de mostrar el curso {{ $curso->name }}</h1>
    <a href="{{ route('cursos.index') }}">Volver a los cursos</a><br>
    <a href="{{ route('cursos.edit', $curso) }}">Editar curso</a>
    <p><strong>Categoria: </strong>{{ $curso->category }}</p>
    <p>{{ $curso->description }}</p>

    <form action="{{ route('cursos.destroy', $curso) }}" method="POST">
        @csrf
        @method('delete')
        <button type="submit">Eliminar</button>
    </form>
@endsection

resources/views/home.blade.php
@extends('layouts.plantilla')

@section('title', 'Mi blog')

@section('content')
<h1>Bienvenido a la pagina principal</h1>
@endsection

resources/views/layouts/partials/footer.blade.php
<footer>
    Es el maldito footer
</footer>

resources/views/layouts/partials/header.blade.php
<header>
    <h1>Coders free</h1>
    <nav>
        <ul>
            <li>
                <a href="{{ route('home') }}" class="{{ request()->routeIs('home') ? 'active' : '' }}">
                    Home
                </a>
            </li>
            <li>
                <a href="{{ route('cursos.index') }}" class="{{ request()->routeIs('cursos.*') ? 'active' : '' }}">
                    Cursos
                </a>
            </li>
            <li>
                <a href="{{ route('nosotros') }}" class="{{ request()->routeIs('nosotros') ? 'active' : '' }}">
                    Nosotros
                </a>
            </li>
            <li>
                <a href="{{ route('contactanos.index') }}" class="{{ request()->routeIs('contactanos.index') ? 'active' : '' }}">
                    Contactanos
                </a>
            </li>
        </ul>
    </nav>
</header>

resources/views/layouts/plantilla.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--<link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">-->
    <title>@yield('title')</title>
    <style>
        .active {
            color: red;
            font-weight: bold;
        }

    </style>
</head>

<body>
    @include('layouts.partials.header')
    @yield('content')
    @include('layouts.partials.footer')
</body>

</html>

resources/views/nosotros.blade.php
@extends('layouts.plantilla')

@section('title', 'Nosotros')

@section('content')
<h1>Nosotros</h1>
@endsection